# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # python-version: ["2.7", "3.7", "3.10", "pypy-3.8"]
        # See supported Python release schedule at https://devguide.python.org/#status-of-python-branches
    steps:
    - run: brew install python-launcher  # just to ensure this does not create conflicts
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    #- name: Use Python ${{ matrix.python-version }}
    #  uses: actions/setup-python@v3
    #  with:
    #    python-version: ${{ matrix.python-version }}

    # GitHub Actions has both Python 2 and 3 installed by default. --> BOTH: python √, python2 √, python3 √
    - run: py --list ; echo "python $(python --version)" ; echo "python2 $(python2 --version)" ; echo "python3 $(python3 --version)" || true

    # Let's disable Python 3 --> PY2 ONLY: python √, python2 √, python3 x
    - run: sudo mv /usr/bin/python3.8 /usr/bin/python3.8.disabled
    - run: py --list ; echo "python $(python --version)" ; echo "python2 $(python2 --version)" ; echo "python3 $(python3 --version)" || true

    # Let's disable Python 2 --> NONE: python x, python2 x, python3 x
    - run: sudo mv /usr/bin/python2.7 /usr/bin/python2.7.disabled
    - run: py --list ; echo "python $(python --version)" ; echo "python2 $(python2 --version)" ; echo "python3 $(python3 --version)" || true

    # Let's install PyPy 3 --> PyPy3 ONLY: python x, python2 x, python3 √
    - run: brew install pypy3
    - run: py --list ; echo "python $(python --version)" ; echo "python2 $(python2 --version)" ; echo "python3 $(python3 --version)" || true

    # Let's uninstall pypy3 and enable Python 3 --> Py3 ONLY: python √, python2 x, python3 √
    - run: brew remove pypy3 && sudo mv /usr/bin/python3.8.disabled /usr/bin/python3.8
    - run: py --list ; echo "python $(python --version)" ; echo "python2 $(python2 --version)" ; echo "python3 $(python3 --version)" || true
    # - run: npm run ci

    # - run: npm install
    # - run: npm run ci
    #- name: Coveralls
    #  uses: coverallsapp/github-action@master
    #  with:
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
