name: purl_matrix_tester
on:
  workflow_dispatch:
jobs:
  purl_matrix_tester:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4  # Don't abuse purl.org
      matrix:
        purl_domain:
          - claussoft
          - AERO
          - AeroLectures
          - AircraftDesign
          - BV-NFC
          - CabinAir
          - Corona
          - EcoLabel
          - EWADE
          - HAW
          - INRMM-MiD
          - Novoa
          - ProfScholz
          - SCAD
          - TCAD
          - ArchOnto
    steps:
      - run: python3 -m pip install tqdm
      - run: python3 -m pip install internetarchive
      - run: ia search purl_${{ matrix.purl_domain }}
      - run: |
          URL=https://purl.org/
          URL_BASE="https://purl.org"
          URL_BASE="https://www-purl-mixedcase-not-working.dev.archive.org"
          ia search purl_${{ matrix.purl_domain }} || ia list purl_${{ matrix.purl_domain }}
          # ia search purl_${{ matrix.purl_domain }}  # Is the case (upper, lower, mixed) correct?
          # ia list purl_${{ matrix.purl_domain }}  # Are there files for this PURL domain?
          curl --fail -X GET $URL_BASE/${{ matrix.purl_domain }}  # Can PURL find this domain?
