name: purl_tester
on:
  workflow_dispatch:
    inputs:
      purl_domain:
        description: 'PURL domain to test.  Ex. "claussoft"'
        required: true
jobs:
  purl_tester:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing ${{ github.event.inputs.purl_domain }}..."
      # - run: python3 -m pip install tqdm
      - run: python3 -m pip install internetarchive
      - run: |
          ia --version
          ia list purl_${{ github.event.inputs.purl_domain }}
          curl --version || true
          URL=https://purl.archive.org/${{ github.event.inputs.purl_domain }}
          echo $URL
          curl -X GET $URL
          sleep 0.5
          URL=https://purl.archive.org/domain/${{ github.event.inputs.purl_domain }}
          echo $URL
          curl -X GET $URL
          sleep 0.5
          URL=https://archive.org/purl_${{ github.event.inputs.purl_domain }}
          echo $URL
          curl -X GET $URL
          sleep 0.5
          URL=$URL/purl_${{ github.event.inputs.purl_domain }}_purl.json
          echo $URL
          curl -X GET $URL
