name: purl_tester
on:
  workflow_dispatch:
    inputs:
      purl_domain:
        description: 'PURL domain to test.  Ex. "claussoft"'
        required: true
jobs:
  purl_tester:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing ${{ github.event.inputs.purl_domain }}..."
      - run: python3 -m pip install tqdm
      - run: python3 -m pip install httpx internetarchive
      - run: |
          ia --version
          ia list purl_${{ github.event.inputs.purl_domain }}
          curl --version || true
          curl -X GET https://purl.archive.org/${{ github.event.inputs.purl_domain }} || true
          sleep 0.5
          curl -X GET https://purl.archive.org/${{ github.event.inputs.purl_domain }} || true 
