name: purl_tester
on:
  workflow_dispatch:
    inputs:
      purl_domain:
        description: 'PURL domain to test.  Ex. "claussoft"'
        required: true
jobs:
  purl_tester:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing ${{ github.event.inputs.purl_domain }}..."
      - run: python3 -m pip install httpx internetarchive requests
      - run: ia --version && ia list ${{ github.event.inputs.purl_domain }}
      - run: curl --version || true
      - run: curl -X GET https://purl.archive.org/${{ github.event.inputs.purl_domain }} || true
      - run: sleep 0.5
      - run: curl -X GET https://purl.archive.org/${{ github.event.inputs.purl_domain }} || true 
